// This runner is auto-generated by Brittle

runTests()

// Cleanup args when running using brittle-node or brittle-bare
const argv = (global?.Bare?.argv ?? global?.process.argv)
if (!/\/test\/all\.js$/.test(argv?.[1])) {
  const execPath = argv[0]
  if (global.Bare) {
    global.Bare.argv.length = 0
    global.Bare.argv.push(execPath, __filename)
  } else {
    process.argv = [execPath, __filename]
  }
}

if (!require.main.url) require.main.url = require('url-file-url').pathToFileURL(__filename)
Error.stackTraceLimit = Infinity
async function runTests () {
  const test = (await import('brittle')).default
  test.pause()

  await import('./constants.test.js')
  await import('./crasher.test.js')
  await import('./errors.test.js')
  await import('./gunk.test.js')
  await import('./index.test.js')
  await import('./logger.test.js')
  await import('./opwait.test.js')
  await import('./link.test.js')
  await import('./state.test.js')
  await import('./teardown.test.js')
  await import('./transform.test.js')
  await import('./tryboot.test.js')

  test.resume()
}
